### ISSUE TITLE
转推 RSS 的内容中包含 HTML，如何去除

### ISSUE THREAD

**Issue by DemoJameson** [wong2/ifttj#1]
例如我刚创建的提醒 https://m.ruguoapp.com/topics/58f026bb43ef0a001147aab6?username=ded76562-1ebd-460c-8878-cf4ebc850b16

**Comment by wong2** [comment]
我来处理下

**Comment by DemoJameson** [comment]
👏🏻👏🏻👏🏻

**Comment by wong2** [comment]
应该ok了，等下次抓取看看效果

**Comment by theuniverse** [comment]
感谢！

奚奇

2017年4月14日 +0800 11:57 Wang Dàpéng <notifications@github.com>，写道：
