### ISSUE TITLE
似乎新创建的都失败了

### ISSUE THREAD

**Issue by WooDragon** [wong2/ifttj#3]
log提示Applet failed
There was a problem with the Webhooks service.

是不是触发了ifttt的limit，我试了好几次，就算和教程建的一毛一样也不行。

**Comment by wong2** [comment]
抱歉服务器有点问题，现在应该好了

**Comment by WooDragon** [comment]
RSS里有输出了，THX

**Comment by WooDragon** [comment]
又挂掉了……

**Comment by wong2** [comment]
@WooDragon 我的服务器太不稳定了，我迁移到 Heroku 了，之后会好了
