### ISSUE TITLE
消息一直 POST 不成功，返回 500

### ISSUE THREAD

**Issue by DemoJameson** [wong2/ifttj#5]
![image](https://user-images.githubusercontent.com/181192/36823231-fc09b660-1d36-11e8-80cb-6951fb98c8c9.png)
源 RSS：https://blog.jetbrains.com/kotlin/feed/
IFTTJ：http://ifttj.wong2.me/rJXdv2Y6e

**Comment by wong2** [comment]
不好意思，前段时间有些问题，现在正常了
